#!/bin/sh

STAGED_FILES=$(git diff --cached --diff-filter=ACMR --name-only -- '*.go')

if test -z "$STAGED_FILES"; then
    echo "No Go Files to Update"
else
    for file in $STAGED_FILES; do
        go fmt "$file"
        git add "$file"
    done
fi
